### ISSUE TITLE
Make app available in F-Droid or as apk file

### ISSUE THREAD

**Issue by m-rey** [Hamza417/Positional#7]
Hello!

It would be great if users could install this app from sources other than the Google play store. Maybe by making it available in F-Droid or at least by adding the app as an apk file when a release is made.

**Comment by Hamza417** [comment]
> making it available in F-Droid

Currently uploading to F-Droid poses various challenges towards app nature i.e. I will have to replace Google Maps with an open source alternative adding extra codes to manage for different flavors and will add more workload for a relatively simple app and last point is managing app on F-Droid is quite difficult as well which will waste more time. I will reconsider this maybe in future.

> adding the app as an apk file when a release is made

Noted, I will add the <b>Free</b> apk with every future releases.

**Comment by m-rey** [comment]
> Noted, I will add the Free apk with every future releases. Does your device supports Play Services?

Yes it does. Thank you for your effort.

**Comment by m-rey** [comment]
I see that it got implemented. Thanks!

I'm closing this issue.

**Comment by plonibarploni** [comment]
The last two releases do not include the APK anymore.

**Comment by Hamza417** [comment]
Added APK for Build120, [See Here](https://github.com/Hamza417/Positional/releases/tag/Build120).

**Comment by Hamza417** [comment]
There was a OSM variant but later suspended due to OSM MapView wasn't stable to rely enough to provide LTS version. It was removed in [Build125](https://github.com/Hamza417/Positional/releases/tag/Build125) and might still be available in older builds.
