### ISSUE TITLE
I'd have purchased full version if there was a high contrast mode, black background with bright roads, similar to the night mode but roads not just mediumdark grey. Intention would be to display current location and surroundings as a motorbike map, benefiting from peripheral vision, therefore the high contrast mode. As is, I find the contrast not high enough.

### ISSUE THREAD

**Issue by Bushmills** [Hamza417/Positional#8]

**Comment by Hamza417** [comment]
I get it, can you post a reference of a motorbike map or any photo that resembles closely to your map design requirements ?

**Comment by Bushmills** [comment]
I don't have a single app showing exactly what I'm looking for.  GPX viewer pro in "toner" mode with reversed screen colours is an approximation, but I'm mostly using OsmAND with a configuration with the highest contrast I could manage, which looks about like this:

**Comment by Bushmills** [comment]
I'll upload the screenshot later on when behind a computer, rather than mobile, again, as I can't include the picture here and now.

**Comment by Hamza417** [comment]
Understood, take your time meanwhile I will do my own research about your problem and think of a feasible solution to your problem

**Comment by Bushmills** [comment]
![Screenshot_20210317-133406_OsmAnd+](https://user-images.githubusercontent.com/1392204/111482634-5fc92900-8734-11eb-905e-7ece5f3d018e.png)
Here's a rough OsmAND approximation. Not perfect, though: The background could be #000000, roads #ffffff, and as you can see, buildings have been configured to not show at all. Though having those in darkish grey could be ok too.
Street names should not necessarily show - here they do when zooming in - but names of villages and towns should. Capability to configure display width of roads would be great.
Idea is, of course, to pay as little attention as possible to the map, as any distraction from the road has potential to increase the risk, especially on a motorbike. Therefore the high contrast, so one can glimpse the oncoming course without the need to focus on the map.

I've been looking at many nav- and map displaying apps, but none I've yet found which combines the above display features to something better than a coarse approximation. I'm confident that such a display mode could give your app a distinguishing characteristic which may make it popular among motorbike riders.

**Comment by Hamza417** [comment]
I have added the High Contrast map option in [Build77](https://github.com/Hamza417/Positional/releases/tag/Build77) using the configuration files available [here](https://github.com/Hamza417/Positional/tree/master/app/src/main/res/raw). This should be usable enough for now. Thank you for the suggestion :)

**Comment by Hamza417** [comment]
Are you available?

**Comment by Hamza417** [comment]
Your telegram handle is not available, so I messaged here. Are you available on Telegram?
